-- The sequence of triangle numbers is generated by adding the natural numbers. 
-- So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
-- The first ten terms would be:
-- 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
-- Let us list the factors of the first seven triangle numbers:
--  1: 1
--  3: 1,3
--  6: 1,2,3,6
-- 10: 1,2,5,10
-- 15: 1,3,5,15
-- 21: 1,3,7,21
-- 28: 1,2,4,7,14,28
-- We can see that 28 is the first triangle number to have over five divisors.
-- What is the value of the first triangle number to have over 
-- five hundred divisors?

triangleNumber i = div (i * (i + 1)) 2
triangles = map triangleNumber [1..]

isqrt n = floor $ sqrt $ fromIntegral n

boolToInt True = 1
boolToInt False = 0

divisors n = asd * 2 - boolToInt ((isqrt n)^2 == n)
    where
        asd = length $ filter (\x-> mod n x == 0) [1..isqrt n]

main :: IO ()
-- main = print $ take 1 $ filter (\n -> length (factors n) > 500) [1..]
--     where factors n = filter (\x-> mod n x == 0)  [1..n]
main = print $ head $ filter (\n -> divisors n > 500) triangles
